class Bible {
  static List<Book> oldTestament = [
    Book(index: 1, name: "Genesis", count: 50),
    Book(index: 2, name: "Exodus", count: 40),
    Book(index: 3, name: "Leviticus", count: 27),
    Book(index: 4, name: "Numbers", count: 36),
    Book(index: 5, name: "Deuteronomy", count: 34),
    Book(index: 6, name: "Joshua", count: 24),
    Book(index: 7, name: "Judges", count: 21),
    Book(index: 8, name: "Ruth", count: 4),
    Book(index: 9, name: "1 Samuel", count: 31),
    Book(index: 10, name: "2 Samuel", count: 24),
    Book(index: 11, name: "1 Kings", count: 22),
    Book(index: 12, name: "2 Kings", count: 25),
    Book(index: 13, name: "1 Chronicles", count: 29),
    Book(index: 14, name: "2 Chronicles", count: 36),
    Book(index: 15, name: "Ezra", count: 10),
    Book(index: 16, name: "Nehemiah", count: 13),
    Book(index: 17, name: "Esther", count: 10),
    Book(index: 18, name: "Job", count: 42),
    Book(index: 19, name: "Psalms", count: 150),
    Book(index: 20, name: "Proverbs", count: 31),
    Book(index: 21, name: "Ecclesiastes", count: 12),
    Book(index: 22, name: "Songs of Solomon", count: 8),
    Book(index: 23, name: "Isaiah", count: 66),
    Book(index: 24, name: "Jeremiah", count: 52),
    Book(index: 25, name: "Lamentations", count: 5),
    Book(index: 26, name: "Ezekiel", count: 48),
    Book(index: 27, name: "Daniel", count: 12),
    Book(index: 28, name: "Hosea", count: 14),
    Book(index: 29, name: "Joel", count: 3),
    Book(index: 30, name: "Amos", count: 9),
    Book(index: 31, name: "Obadiah", count: 1),
    Book(index: 32, name: "Jonah", count: 4),
    Book(index: 33, name: "Micah", count: 7),
    Book(index: 34, name: "Nahum", count: 3),
    Book(index: 35, name: "Habakkuk", count: 3),
    Book(index: 36, name: "Zephaniah", count: 3),
    Book(index: 37, name: "Haggai", count: 2),
    Book(index: 38, name: "Zechariah", count: 14),
    Book(index: 39, name: "Melachi", count: 4),
  ];
  static List<Book> newTestament = [
    Book(index: 40, name: "Matthew", count: 24),
    Book(index: 41, name: "Mark", count: 16),
    Book(index: 42, name: "Luke", count: 24),
    Book(index: 43, name: "John", count: 21),
    Book(index: 44, name: "Acts", count: 28),
    Book(index: 45, name: "Romans", count: 16),
    Book(index: 46, name: "1 Corinthians", count: 16),
    Book(index: 47, name: "2 Corinthians", count: 13),
    Book(index: 48, name: "Galatians", count: 6),
    Book(index: 49, name: "Ephesians", count: 6),
    Book(index: 50, name: "Philippians", count: 4),
    Book(index: 51, name: "Colossians", count: 4),
    Book(index: 52, name: "1 Thessalonians", count: 5),
    Book(index: 53, name: "2 Thessalonians", count: 3),
    Book(index: 54, name: "1 Timothy", count: 6),
    Book(index: 55, name: "2 Timothy", count: 4),
    Book(index: 56, name: "Titus", count: 3),
    Book(index: 57, name: "Philemon", count: 1),
    Book(index: 58, name: "Hebrews", count: 13),
    Book(index: 59, name: "James", count: 5),
    Book(index: 60, name: "1 Peter", count: 5),
    Book(index: 61, name: "2 Peter", count: 3),
    Book(index: 62, name: "1 John", count: 4),
    Book(index: 63, name: "2 John", count: 1),
    Book(index: 64, name: "3 John", count: 1),
    Book(index: 65, name: "Jude", count: 1),
    Book(index: 66, name: "Revelations", count: 22),
  ];
  static List<Book> mixed = [
    Book(index: 1, name: "Genesis", count: 50),
    Book(index: 2, name: "Exodus", count: 40),
    Book(index: 3, name: "Leviticus", count: 27),
    Book(index: 4, name: "Numbers", count: 36),
    Book(index: 5, name: "Deuteronomy", count: 34),
    Book(index: 6, name: "Joshua", count: 24),
    Book(index: 7, name: "Judges", count: 21),
    Book(index: 8, name: "Ruth", count: 4),
    Book(index: 9, name: "1 Samuel", count: 31),
    Book(index: 10, name: "2 Samuel", count: 24),
    Book(index: 11, name: "1 Kings", count: 22),
    Book(index: 12, name: "2 Kings", count: 25),
    Book(index: 13, name: "1 Chronicles", count: 29),
    Book(index: 14, name: "2 Chronicles", count: 36),
    Book(index: 15, name: "Ezra", count: 10),
    Book(index: 16, name: "Nehemiah", count: 13),
    Book(index: 17, name: "Esther", count: 10),
    Book(index: 18, name: "Job", count: 42),
    Book(index: 19, name: "Psalms", count: 150),
    Book(index: 20, name: "Proverbs", count: 31),
    Book(index: 21, name: "Ecclesiastes", count: 12),
    Book(index: 22, name: "Songs of Solomon", count: 8),
    Book(index: 23, name: "Isaiah", count: 66),
    Book(index: 24, name: "Jeremiah", count: 52),
    Book(index: 25, name: "Lamentations", count: 5),
    Book(index: 26, name: "Ezekiel", count: 48),
    Book(index: 27, name: "Daniel", count: 12),
    Book(index: 28, name: "Hosea", count: 14),
    Book(index: 29, name: "Joel", count: 3),
    Book(index: 30, name: "Amos", count: 9),
    Book(index: 31, name: "Obadiah", count: 1),
    Book(index: 32, name: "Jonah", count: 4),
    Book(index: 33, name: "Micah", count: 7),
    Book(index: 34, name: "Nahum", count: 3),
    Book(index: 35, name: "Habakkuk", count: 3),
    Book(index: 36, name: "Zephaniah", count: 3),
    Book(index: 37, name: "Haggai", count: 2),
    Book(index: 38, name: "Zechariah", count: 14),
    Book(index: 39, name: "Melachi", count: 4),
    Book(index: 40, name: "Matthew", count: 24),
    Book(index: 41, name: "Mark", count: 16),
    Book(index: 42, name: "Luke", count: 24),
    Book(index: 43, name: "John", count: 21),
    Book(index: 44, name: "Acts", count: 28),
    Book(index: 45, name: "Romans", count: 16),
    Book(index: 46, name: "1 Corinthians", count: 16),
    Book(index: 47, name: "2 Corinthians", count: 13),
    Book(index: 48, name: "Galatians", count: 6),
    Book(index: 49, name: "Ephesians", count: 6),
    Book(index: 50, name: "Philippians", count: 4),
    Book(index: 51, name: "Colossians", count: 4),
    Book(index: 52, name: "1 Thessalonians", count: 5),
    Book(index: 53, name: "2 Thessalonians", count: 3),
    Book(index: 54, name: "1 Timothy", count: 6),
    Book(index: 55, name: "2 Timothy", count: 4),
    Book(index: 56, name: "Titus", count: 3),
    Book(index: 57, name: "Philemon", count: 1),
    Book(index: 58, name: "Hebrews", count: 13),
    Book(index: 59, name: "James", count: 5),
    Book(index: 60, name: "1 Peter", count: 5),
    Book(index: 61, name: "2 Peter", count: 3),
    Book(index: 62, name: "1 John", count: 4),
    Book(index: 63, name: "2 John", count: 1),
    Book(index: 64, name: "3 John", count: 1),
    Book(index: 65, name: "Jude", count: 1),
    Book(index: 66, name: "Revelations", count: 22),
  ];
}

class Book {
  final int index;
  final String name;
  int tag = 0;
  final int count;
  Book({required this.index, required this.name, required this.count});
}

class SelectedBook {
  int book;
  int chapter;
  String bookName = "";
  SelectedBook({required this.book, required this.chapter, this.bookName = ""});
}
